name: Build and Push Docker image to GCPArtifact Registry

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Create .env file
        run: |
          echo "AT_API_KEY=${{ secrets.AT_API_KEY }}" > .env

      - name: Build Docker image
        run: |
          make build_docker_image

      - name: Tag Docker image
        run: |
          make tag_docker_image_for_gcp

      - name: Push Docker image to Artifact Registry
        run: |
          make push_docker_image_to_gcp

  update-vm-image-on-airflow-server:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Trigger repository dispatch
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ vars.AIRFLOW_REPOSITORY_OWNER }}
          repo: ${{ vars.AIRFLOW_REPOSITORY }}
          github_token: ${{ secrets.GH_TOKEN }}
          workflow_file_name: ${{ vars.WORKFLOW_TRIGGERED_DEPLOY_DAGS }}
          client_payload: '{"docker_image_name":"at-bus-load:latest"}'