name: Python Lint and Type Check

on:
  push:
    branches: [ main, build-push-docker-image ]

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync --locked

    - name: Lint with Ruff
      run: |
        make ruff_check

    - name: Type check with Mypy
      run: |
        make mypy

